apiVersion: v1
kind: Service
metadata:
  name: {{ include "wiki.backend.fullname" . }}
  labels:
    {{- include "wiki.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "wiki.selectorLabels" (dict "root" . "component" "backend") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.backendPort }}
      targetPort: http
